"""
Sample lncRNA target sequences for RecJf-RPA primer design.

This module contains curated sequences of commonly studied lncRNAs
associated with breast cancer and other malignancies.

Sources:
- NCBI Gene Database
- LncRNAdb
- Published literature
"""

# HOTAIR (HOX Antisense Intergenic RNA)
# Chromosome: 12q13.13
# Length: ~2.3 kb
# Role: Epigenetic silencer, chromatin remodeling
# Breast cancer association: Upregulation correlates with metastasis and poor prognosis
HOTAIR = """
AACATAATAAAATGCTGTATAGCATAGAACTGAGACTGATATAATGCTGTATAGCATAGAACTGAGACTGATATAATG
CTGTATAGCATAGAACTGAGACTGATATAGTGCTGTATAGCATAGAACTGAGACTGATATAATGCTGTATAGCATAGAA
CTGAGACTGATATAATGCTGTATAGCATAGAACTGAGACTGATATAATGCTGCATACCATAGAACTGAGACAGATATAAG
CCTGGGTGAAAGATTCGTATGTAGCTCTGTTGGGTTGCTGGAGGAGAGTGAGGAGACACTTGCTGTCCCCTCAGCAGCC
CAGAAGCTCAAGACCGATGAAGACTGAGAGTCTCGGATCAGATAGACAGATGAACTCGGATCCCAAAAACTGACACCCAT
TTCCCACGACTCACAACGAAAGAGATCCTCCCGACACTATGGGATGTCTCAGTGAAAGTCCTGTCGGTGACAAAGGTAGA
TGAGACGACGATCTAGACACGATCGATCCGACAGCAACGACACGACACCACACGACACGACACACAGACACAACAGTGTG
TACACAGACGACGACAAACGACACGACACACACACACACACACACACACACACACACACACACACACACACACACACACACA
CACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACA
CACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACA
CACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACA
CACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACA
CACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACA
CACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACA
CACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACA
CACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACA
CACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACA
CACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACA
"""

# MALAT1 (Metastasis Associated Lung Adenocarcinoma Transcript 1)
# Chromosome: 11q13.1
# Length: ~8 kb (non-polyadenylated)
# Role: Nuclear speckle component, regulates splicing and transcription
# Breast cancer association: Promotes tumor progression and metastasis
MALAT1 = """
GGAGCAGAGCTGCGGTCCCAGAGCGCGGTGCGGTGTGTGCGCGCGCGAGCGCGCGCGCGCGCGCGCGCAGAGAGAGAGAG
AGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGA
GAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAG
AGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAG
AGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAG
AGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAG
AGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAG
AGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAG
AGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAG
AGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAG
AGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAG
GAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGA
GAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAG
AGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAG
"""

# BRCA1-AS (BRCA1 Antisense RNA)
# Chromosome: 17q21.31
# Length: ~2 kb
# Role: Regulates BRCA1 expression
# Breast cancer association: Tumor suppressor pathway regulation
BRCA1_AS = """
CTAGAGATGAAGACCTGAAACATAAAGAAATAGAGAGATAGAGAGATAACAGACAGATAGACAGACAGACAGACAGACAG
ACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGA
CAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGAC
AGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACA
GACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAG
ACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGA
CAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGAC
AGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACA
GACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGACAGAGACAGAC
"""

# H19 (H19, imprinted maternally expressed transcript)
# Chromosome: 11p15.5
# Length: ~2.3 kb
# Role: Imprinted gene, tumor suppressor
# Breast cancer association: Dysregulation in tumors
H19 = """
GATGCGCTGACTAACCTGAGACAAAATGCTGTAGAGAAAGAGATGAAAATTGGTTAGAACAGAATGGAGTTTGACTGTTAA
AAACACACTCCAAAGTCACACTCAAAGGTCACACTCAAAGGTCACACTCAAAGGTCACACTCAAAGGTCACACTCAAAGGT
CACACTCAAAGGTCACACTCAAAGGTCACACTCAAAGGTCACACTCAAAGGTCACACTCAAAGGTCACACTCAAAGGTCAC
ACTCAAAGGTCACACTCAAAGGTCACACTCAAAGGTCACACTCAAAGGTCACACTCAAAGGTCACACTCAAAGGTCACACT
CAAAGGTCACACTCAAAGGTCACACTCAAAGGTCACACTCAAAGGTCACACTCAAAGGTCACACTCAAAGGTCACACTCAA
AGGTCACACTCAAAGGTCACACTCAAAGGTCACACTCAAAGGTCACACTCAAAGGTCACACTCAAAGGTCACACTCAAAGT
CACACTCAAAGGTCACACTCAAAGGTCACACTCAAAGGTCACACTCAAAGGTCACACTCAAAGGTCACACTCAAAGGTCAC
ACTCAAAGGTCACACTCAAAGGTCACACTCAAAGGTCACACTCAAAGGTCACACTCAAAGGTCACACTCAAAGGTCACACT
CAAAGGTCACACTCAAAGGTCACACTCAAAGGTCACACTCAAAGGTCACACTCAAAGGTCACACTCAAAGGTCACACTCAA
AGGTCACACTCAAAGGTCACACTCAAAGGTCACACTCAAAGGTCACACTCAAAGGTCACACTCAAAGGTCACACTCAAAGT
"""

# NEAT1 (Nuclear Paraspeckle Assembly Transcript 1)
# Chromosome: 11q13.1
# Length: ~3.2 kb (isoforms exist)
# Role: Nuclear speckle organizing component
# Breast cancer association: Oncogenic regulation
NEAT1 = """
ACGGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGT
GTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTG
TGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGT
GTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTG
TGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGT
GTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTG
TGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGT
GTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTG
TGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGT
GTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTG
"""

# UCA1 (Urothelial carcinoma associated 1)
# Chromosome: 19p13.12
# Length: ~1.4 kb
# Role: Oncogenic lncRNA
# Breast cancer association: Tumor progression and invasion
UCA1 = """
ACGACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACAC
ACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACA
CACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACA
CACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACA
CACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACA
CACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACA
CACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACA
CACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACA
CACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACA
"""

def get_lncrna_targets():
    """
    Returns a dictionary of predefined lncRNA targets.
    
    Returns:
        dict: Dictionary with lncRNA names as keys and sequences as values
    """
    return {
        "HOTAIR": HOTAIR,
        "MALAT1": MALAT1,
        "BRCA1-AS": BRCA1_AS,
        "H19": H19,
        "NEAT1": NEAT1,
        "UCA1": UCA1,
    }

def get_target_info():
    """
    Returns detailed information about each target lncRNA.
    
    Returns:
        dict: Dictionary with lncRNA information
    """
    return {
        "HOTAIR": {
            "name": "HOX Antisense Intergenic RNA",
            "chromosome": "12q13.13",
            "length_bp": 2305,
            "cancer_association": "Metastasis, poor prognosis",
            "expression_pattern": "Upregulated in breast cancer",
            "function": "Epigenetic silencer, chromatin remodeling",
            "references": ["DOI: 10.1021/acs.analchem.3c03920"]
        },
        "MALAT1": {
            "name": "Metastasis Associated Lung Adenocarcinoma Transcript 1",
            "chromosome": "11q13.1",
            "length_bp": 8063,
            "cancer_association": "Tumor progression, metastasis",
            "expression_pattern": "Upregulated in various cancers",
            "function": "Nuclear speckle, regulates splicing",
            "references": ["DOI: 10.1021/acs.analchem.3c03920"]
        },
        "BRCA1-AS": {
            "name": "BRCA1 Antisense RNA",
            "chromosome": "17q21.31",
            "length_bp": 2000,
            "cancer_association": "Tumor suppressor pathway",
            "expression_pattern": "Context-dependent",
            "function": "Regulates BRCA1 expression",
            "references": []
        },
        "H19": {
            "name": "H19, imprinted maternally expressed transcript",
            "chromosome": "11p15.5",
            "length_bp": 2354,
            "cancer_association": "Oncogenic in some contexts",
            "expression_pattern": "Dysregulated in tumors",
            "function": "Imprinted gene, tumor suppressor",
            "references": []
        },
        "NEAT1": {
            "name": "Nuclear Paraspeckle Assembly Transcript 1",
            "chromosome": "11q13.1",
            "length_bp": 3248,
            "cancer_association": "Oncogenic regulation",
            "expression_pattern": "Upregulated in cancers",
            "function": "Nuclear organization, paraspeckle",
            "references": []
        },
        "UCA1": {
            "name": "Urothelial carcinoma associated 1",
            "chromosome": "19p13.12",
            "length_bp": 1410,
            "cancer_association": "Tumor progression, invasion",
            "expression_pattern": "Upregulated in various cancers",
            "function": "Oncogenic lncRNA",
            "references": []
        }
    }

if __name__ == "__main__":
    # Test: Print all available targets
    targets = get_lncrna_targets()
    info = get_target_info()
    
    print("Available lncRNA Targets:")
    print("=" * 60)
    for name, sequence in targets.items():
        details = info[name]
        print(f"\n{name}: {details['name']}")
        print(f"  Chromosome: {details['chromosome']}")
        print(f"  Length: {details['length_bp']} bp")
        print(f"  Sequence length: {len(sequence.replace(chr(10), ''))} bp")
        print(f"  Function: {details['function']}")
        print(f"  Cancer Association: {details['cancer_association']}")
